### PR TITLE
New enemies sprite

### PR DESCRIPTION
**Pull request by JunZH0**
Added slime. acid slime and skeleton sprite

### CODE REVIEW

**Comment by JunZH0** [comment]
added changes

**Review by alexaib2002 — CHANGES_REQUESTED** [review]
Goblin sprite license is missing

**Review by alexaib2002 — APPROVED** [review]
Everything looks alright, approved for merging

**Comment by alexaib2002** [comment]
Had to rename typo on merge with LICENCE_MANIFEST (was called LICENCE_MANI-S-FEST on this branch)

**Pull request merged**
